### PR TITLE
make it work with ezplatform v2

### PR DESCRIPTION
**Pull request by crevillo**
it just modifies composer.json in order to make this bundle installable with ezplatform v2.

ping @bdunogier @janit

### CODE REVIEW

**Comment by bdunogier** [comment]
Great, thank you.
I guess you did check that it works ? @janit has had issues with it, iirc.

**Comment by crevillo** [comment]
well, my point for this was only to make it installable because composer install failed if not. but otoh, i discoverd the fork of @janit, so it he can jump and add his input, i could test it...

**Comment by janit** [comment]
Hi, I think this should work fine with `7.0.x` kernel and GraphQLBundle `0.6.x`.

I did notice that the API has changed in the GraphQLBundle from Overblog in version `0.7.0`, later versions do work - but fields return null value. I encountered this while trying to add a custom scalar for DateTimes: https://github.com/overblog/GraphQLBundle/blob/master/Resources/doc/definitions/type-system/scalars.md#custom-scalar

The GraphQLBundle version `0.6.x` does not have custom scalar definitions. Keeping this version and Writing a resolver worked, as shown in my fork: https://github.com/janit/ezplatform-graphql-bundle/blob/datehack/GraphQL/Resolver/DateTimeResolver.php

**Comment by crevillo** [comment]
if it helps, i'm working in another project having api-platform as base. this api-platform uses also that graphql bundle. today i've seen some people at slack having similar issues, @janit

**Pull request merged**
